Fix compile error
espressif/esp-lwip pull request #21
Opened 2020-09-02 16:57 UTC by vinhjaxt

At `./src/include/lwip/ip4_addr.h` line `51`:
```c
struct ip4_addr {
  u32_t addr;
};
```
So I changed `ip_addr.u_addr.ip4.addr` to `ip_addr.addr` to fix the compile error on my esp8266 project.

2020-09-03 07:20 UTC, Alvin1Zhang commented
Thanks for your contribution.

2020-09-08 12:37 UTC, david-cermak commented
Hi @vinhjaxt 

The thing is that the [ip4_napt](https://github.com/espressif/esp-lwip/blob/2.1.2-esp/src/core/ipv4/ip4_napt.c#L179) uses the `ip_addr` defined in [netif](https://github.com/espressif/esp-lwip/blob/2.1.2-esp//src/include/lwip/netif.h#L278) as struct of this [`union`](https://github.com/espressif/esp-lwip/blob/2.1.2-esp//src/include/lwip/ip_addr.h#L73) thus the referencing is correct.

How do you compile your 8266 project with the `esp-lwip`?

2020-09-14 10:37 UTC, vinhjaxt commented
Hi @david-cermak ,
Here we go:
```
git clone https://github.com/espressif/ESP8266_RTOS_SDK.git 
cd ESP8266_RTOS_SDK/examples/get-started/hello_world/
make menuconfig
--> Component config
    --> LWIP
        [*] Enable copy between Layer2 and Layer3 packets
        [*] Enable IP forwarding
        [*]     Enable NAT (new/experimental) (NEW)
make
```

2020-09-15 16:17 UTC, david-cermak commented
@vinhjaxt 
Would it help if you also enable IPv6 in menuconfig?
```
make menuconfig
--> Component config
    --> LWIP
        [*] CONFIG_LWIP_IPV6 -> 1
```

The trouble is that the changes you are proposing break IDF builds.

2020-09-15 16:22 UTC, david-cermak requested changes
These changes break builds for all esp-idf configuration and also if `CONFIG_LWIP_IPV6=1` for 8266.

We have to address situations when LWIP is configured to
* `LWIP_IPV6==1 && LWIP_IPV4==1`
* `LWIP_IPV6==0 && LWIP_IPV4==1`
* (`LWIP_IPV6==1 && LWIP_IPV4==0`)

2020-12-19 14:41 UTC, closed without merging