napt: Fixes and improvements
espressif/esp-lwip pull request #43
Opened 2022-02-24 23:47 UTC by rojer

1. Fix enable/disable to properly allocate and deallocate tables.
    Current algorithm is just broken.
 2. Introduce eviction policy when table gets full: oldest connection
    is evicted, instead of new ones getting silently dropped. this
    results in much better behavior with small tables than before.
    When TCP connection is dropped, RSTs are sent both ways to inform
    parties instead of dropping silently. thiw requires additional 8
    bytes per entry but is, again, a big improvement for clients in
    terms of usability.
 3. FIxed handling of timestamp wraparound (every ~50 days of uptime).
 3. Added ip_portmap_get() to retrieve current port mapping settings.
 4. Added ip_napt_get_stats() for some insight into the state of NAT.

2022-03-01 01:29 UTC, Alvin1Zhang commented
Thanks for your contribution.

2022-03-10 12:07 UTC, david-cermak requested changes
Thanks for the fixes! LGTM in general

2022-03-10 12:07 UTC, david-cermak commented on src/core/ipv4/ip4_napt.c
> +void
Could this still be static?
```suggestion
static void
```

2022-03-10 12:07 UTC, david-cermak commented on src/core/ipv4/ip4_napt.c
> +  if (ip_napt_table) mem_free(ip_napt_table);
we assume `free(NULL)` is a valid statement, the same for the line below.
```suggestion
  mem_free(ip_napt_table);
```

2022-03-10 12:07 UTC, david-cermak commented on src/core/timeouts.c
> +  {NAPT_TMR_INTERVAL, HANDLER(ip_napt_tmr)},
Could we use `sys_timeout(...)` directly from the napt module to avoid changes in `src/core/timeouts.c`

2022-03-10 12:07 UTC, david-cermak commented on src/core/ipv4/ip4_napt.c
> +  u32_t src;   // net
Please use C90 style comments only

2022-03-10 12:10 UTC, david-cermak commented
> Current algorithm is just broken.

It would be nice to cover this in the test cases.

Also, the current NAPT test suite fails (on compilation):
```
../../../../src/core/ipv4/ip4_napt.c:64:16: error: C++ style comments are incompatible with C90 [-Werror]
   u32_t src;   // net
                ^
```
To run the lwip unit tests on host, please follow these steps:

https://github.com/espressif/esp-lwip/blob/76303df2386902e0d7873be4217f1d9d1b50f982/.gitlab-ci.yml#L33-L46

2022-03-20 18:07 UTC, rojer commented
thanks for the review, all done.
however, i was not able to run the tests as they don't seem to be present in the public repository - there's no `ports/` directory.

2022-03-21 09:17 UTC, david-cermak commented
@rojer Thanks for the update! Seems like you forgot to revert the changes in `src/core/timeouts.c` after using `sys_timeout()`

>  there's no ports/ directory.
The port directory is present in the [contrib](https://git.savannah.nongnu.org/cgit/lwip/lwip-contrib.git) repo. I'm sorry, running the CI locally hasn't been very straight-forward. Currently working on improvements for the upcoming branches using GitHub workflows (so contributors can easily check their work). You can temporarily use these workflows to test your changes, though it's very WIP and present only on my personal fork. Tried to pick your changes [here](https://github.com/david-cermak/esp-lwip/commits/bugfix/napt_picked_on_2.1.3_temp), CI fails with the [forgotten timeout changes](https://github.com/david-cermak/esp-lwip/runs/5624316533?check_suite_focus=true), mentioned above.

2022-03-21 21:41 UTC, rojer commented
> Seems like you forgot to revert the changes in src/core/timeouts.c after using sys_timeout()

yes, you're right, forgot to commit that change. done.

> The port directory is present in the [contrib](https://git.savannah.nongnu.org/cgit/lwip/lwip-contrib.git) repo

ok, i cloned it and checked out STABLE-2_1_0_RELEASE but now check.h is missing:

```
[rojer@nbd ~/cesanta/esp/lwip-contrib 35b011d4cf4c4b480f8859c456587a884ec9d287]$ ./qq.sh 
+ cd ports/unix/check/
+ export LWIPDIR=/home/rojer/cesanta/esp/esp-lwip/src
+ LWIPDIR=/home/rojer/cesanta/esp/esp-lwip/src
+ export CK_DEFAULT_TIMEOUT=1000
+ CK_DEFAULT_TIMEOUT=1000
+ export EXTRA_CFLAGS=
+ EXTRA_CFLAGS=
+ export 'CC=cc '
+ CC='cc '
+ export CCDEP=cc
+ CCDEP=cc
+ make -j 1 check
cc  -DLWIP_NOASSERT_ON_ERROR -I/usr/include/check -I/home/rojer/cesanta/esp/esp-lwip/src/../test/unit -g -DLWIP_DEBUG -Wall -pedantic -Werror -Wparentheses -Wsequence-point -Wswitch-default -Wextra -Wundef -Wshadow -Wpointer-arith -Wcast-qual -Wc++-compat -Wwrite-strings -Wold-style-definition -Wcast-align -Wmissing-prototypes -Wredundant-decls -Wnested-externs -Wunreachable-code -Wuninitialized -Wmissing-prototypes -Wredundant-decls -Waggregate-return -Wlogical-not-parentheses -Wlogical-op -Wc90-c99-compat -Wtrampolines -I. -I../../.. -I/home/rojer/cesanta/esp/esp-lwip/src/include -I../../../ports/unix/port/include -c /home/rojer/cesanta/esp/esp-lwip/src/../test/unit/lwip_unittests.c
In file included from /home/rojer/cesanta/esp/esp-lwip/src/../test/unit/lwip_unittests.c:1:
/home/rojer/cesanta/esp/esp-lwip/src/../test/unit/lwip_check.h:7:10: fatal error: check.h: No such file or directory
    7 | #include <check.h>
      |          ^~~~~~~~~
compilation terminated.
make: *** [/home/rojer/cesanta/esp/lwip-contrib/ports/unix/../Common.allports.mk:91: lwip_unittests.o] Error 1
```

2022-03-21 21:59 UTC, rojer commented
> check.h is missing

`apt-get install check` fixed it.

ok, updated the branch. in addition to issues with my patch i had to fix two other unrelated C90/C99 issues that prevented code from building, i have no idea how it works on the CI but they are legit in C90 mode.

tests are now passing:

```
+ export 'EXTRA_CFLAGS=-DIP_FORWARD=1 -DIP_NAPT=1 -DLWIP_ARCH_CC_H -include cc_esp_platform.h'
+ EXTRA_CFLAGS='-DIP_FORWARD=1 -DIP_NAPT=1 -DLWIP_ARCH_CC_H -include cc_esp_platform.h'
+ export 'CC=cc -DIP_FORWARD=1 -DIP_NAPT=1 -DLWIP_ARCH_CC_H -include cc_esp_platform.h'
+ CC='cc -DIP_FORWARD=1 -DIP_NAPT=1 -DLWIP_ARCH_CC_H -include cc_esp_platform.h'
+ make -j 4 check
...
Running suite(s): IPv4
 IPv6
 UDP
 TCP
 TCP_OOS
 TCP_STATE
 DEF
 MEM
 NETIF
 PBUF
 TIMERS
 ETHARP
 DHCP
 MDNS
 MQTT
 SOCKETS
 IP4_ROUTE
100%: Checks: 126, Failures: 0, Errors: 0
```

2022-03-22 07:52 UTC, david-cermak approved these changes
Thanks again for the update! just some minor nitpicks.

2022-03-22 07:52 UTC, david-cermak commented on src/core/ipv4/ip4_napt.c
> +#include "string.h"
Nitpick (same above)
```suggestion
#include <string.h>
```

2022-03-22 07:52 UTC, david-cermak commented on src/core/ipv4/ip4_napt.c
> +  uint16_t nr_total = napt_stats.nr_active_tcp + napt_stats.nr_active_udp + napt_stats.nr_active_icmp;
Nit + mixed declaration
```suggestion
  u8_t nr_total = ...
```

2022-03-22 07:52 UTC, david-cermak commented on src/core/ipv4/ip4_napt.c
> +     uint8_t p = t->proto;
same here: `u8_t` + mixed decl

2022-03-22 07:52 UTC, david-cermak commented on src/core/ipv4/ip4_napt.c
> +#pragma GCC diagnostic push
I would personally prefer using basic integer types to placing `#pragma`'s into generic lwip code. These directives apparently work in `clang`, so okay with me, feel free to ignore.

2022-03-22 08:00 UTC, david-cermak commented
Nice, that you succeeded in running the tests eventually! Still some issues in the debug prints though:
```
../../../../src/core/ipv4/ip4_napt.c: In function ‘napt_debug_print’:
../../../../src/core/ipv4/ip4_napt.c:143:6: error: ISO C90 forbids mixed declarations and code [-Werror=c90-c99-compat]
  143 |      uint8_t p = t->proto;
      |      ^~~~~~~
```

Please note, that the test with debug logs are not executed in the CI:

https://github.com/espressif/esp-lwip/blob/76303df2386902e0d7873be4217f1d9d1b50f982/.gitlab-ci.yml#L47-L50

just wanted to see how the NAPT tests would work with the newly introduced eviction mechanism you implemented, seems like the oldest record was [removed here](https://github.com/david-cermak/esp-lwip/runs/5640149962?check_suite_focus=true#step:4:4951):

2022-03-22 08:08 UTC, david-cermak commented
Note: I'm passing this PR to an internal review, which usually takes some time until accepted and merged.

2022-03-24 09:15 UTC, david-cermak commented on src/core/ipv4/ip4_napt.c
> +#pragma GCC diagnostic push
One correction, this won't compile in clang:
```bash
clang -DIP_FORWARD=1 -DIP_FORWARD=1 -DIP_NAPT=1 -DLWIP_ARCH_CC_H -include cc_esp_platform.h -DLWIP_NOASSERT_ON_ERROR -I/usr/include/check -I../../../../src/../test/unit -Wno-gnu-zero-variadic-macro-arguments -g -DLWIP_DEBUG -Wall -pedantic -Werror -Wparentheses -Wsequence-point -Wswitch-default -Wextra -Wundef -Wshadow -Wpointer-arith -Wcast-qual -Wc++-compat -Wwrite-strings -Wold-style-definition -Wcast-align -Wmissing-prototypes -Wredundant-decls -Wnested-externs -Wunreachable-code -Wuninitialized -Wmissing-prototypes -Wredundant-decls -Waggregate-return -Wlogical-not-parentheses -fsanitize=address -fsanitize=undefined -fno-sanitize=alignment -Wdocumentation -Wno-documentation-deprecated-sync -I. -I../../.. -I../../../../src/include -I../../../ports/unix/port/include -c ../../../../src/core/ipv6/dhcp6.c
../../../../src/core/ipv4/ip4_napt.c:64:32: error: unknown warning group '-Wc90-c99-compat', ignored [-Werror,-Wunknown-warning-option]
#pragma GCC diagnostic ignored "-Wc90-c99-compat" /* To allow u8_t bit fields */
                               ^
1 error generated.
```
[ci link](https://github.com/david-cermak/esp-lwip/runs/5673607813?check_suite_focus=true)

2022-03-27 21:37 UTC, rojer commented on src/core/ipv4/ip4_napt.c
> +#pragma GCC diagnostic push
so when compiling with the extra bitchy flags GCC complains about the bitfield underlying type being uint8 instead of a unsigned (or signed) int, as per standard. fine. but in practice it works and i don't feel comfortable about adding extra 3 bytes to the size of the struct just to maintain purity.
clang doesn't complain about it, so i ifdefed this out for it, now it builds.

2022-03-27 21:42 UTC, rojer commented
@david-cermak addressed comments, rebased onto most recent 2.1.2-esp

2022-04-14 15:27 UTC, merged